/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const config = require("../../lib/configuration");
const testConfiguration = require("../TestBootstrap");
const baseController = require("../../lib/Controllers/BaseController");

const controller = testerlib.CompaniesController;
const MRegistrations = testerlib.MRegistrations;
const MRegistrationsrequest = testerlib.MRegistrationsrequest;
const HttpsCompaniesHmlCaradhrasIoV1Registrations791d1dbeF6cd48cdA21bDce0dbd83201DocumentsDocumentTypePASSPORT = testerlib.HttpsCompaniesHmlCaradhrasIoV1Registrations791d1dbeF6cd48cdA21bDce0dbd83201DocumentsDocumentTypePASSPORT;
const MRegistrationsRegistrationId = testerlib.MRegistrationsRegistrationId;
const MRegistrationsRegistrationIdRequest = testerlib.MRegistrationsRegistrationIdRequest;
const MRegisteredCompanies9914293 = testerlib.MRegisteredCompanies9914293;
const MRegisteredCompaniesCompanyIdRequest = testerlib.MRegisteredCompaniesCompanyIdRequest;
const MRegistrations791d1dbeF6cd48cdA21bDce0dbd83201 = testerlib.MRegistrations791d1dbeF6cd48cdA21bDce0dbd83201;
const MRegistrationsRegistrationIdC6f09995Af8c4e0f89f41beca1da7b5fDocuments = testerlib.MRegistrationsRegistrationIdC6f09995Af8c4e0f89f41beca1da7b5fDocuments;
const MRegistrationsStatusesStatus = testerlib.MRegistrationsStatusesStatus;
const MRegistrationsCompaniesCNPJPartnersCPF = testerlib.MRegistrationsCompaniesCNPJPartnersCPF;
const MRegisteredCompanies99142931 = testerlib.MRegisteredCompanies99142931;

describe("CompaniesController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * <p>This method submits a company to registration.</p>
<p> </p>


<h2>PARAMETERS<h2>
<table>
<tbody>
<tr>
<td>
<p><strong>PARAMETER</strong></p>
</td>
<td>
<p><strong>DESCRIPTION</strong></p>
</td>
<td>
<p><strong>VALUE</strong></p>
</td>
<td>
<p><strong>REQUIRED</strong></p>
</td>
<td>
<p><strong>RESTRICTIONS</strong></p>
</td>
</tr>
<tr>
<td>
<p><strong> company</strong></p>
</td>
<td>
<p>Company details.</p>
</td>
<td>
<p>Array</p>
</td>
<td> </td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>nationalRegistration</strong></p>
</td>
<td>
<p>Company national registration (CNPJ).</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>size = 14.</p>
</td>
</tr>
<tr>
<td>
<p><strong>legalName</strong></p>
</td>
<td>
<p>Company legal name.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>legalNature</strong></p>
</td>
<td>
<p>Company legal nature.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>size = 4.</p>
</td>
</tr>
<tr>
<td>
<p><strong>legalStatus</strong></p>
</td>
<td>
<p>Company legal status.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>tradeName</strong></p>
</td>
<td>
<p>Company trade name.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>establishmentDate</strong></p>
</td>
<td>
<p>Company foundation date.</p>
</td>
<td>
<p>Date</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>Date in the past; ISO 8601 format.</p>
</td>
</tr>
<tr>
<td>
<p><strong>establishmentFormat</strong></p>
</td>
<td>
<p>Company establishment format.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>[EI, MEI, EIRELI, LTDA, SS, SA, ME, EPP, EMGP].</p>
</td>
</tr>
<tr>
<td>
<p><strong>stateRegistration</strong></p>
</td>
<td>
<p>Company state registration.</p>
</td>
<td>
<p>Integer</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>max size = 16.</p>
</td>
</tr>
<tr>
<td>
<p><strong>email</strong></p>
</td>
<td>
<p>Company mail address.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>revenue</strong></p>
</td>
<td>
<p>Company annual revenue.</p>
</td>
<td>
<p>Double </p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>default: 0.0.</p>
</td>
</tr>
<tr>
<td>
<p><strong>mainCnae</strong></p>
</td>
<td>
<p>Main cnae.</p>
</td>
<td>
<p>Number</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>size =  6 or 7.</p>
</td>
</tr>
<tr>
<td>
<p><strong>cnaes</strong></p>
</td>
<td>
<p>Other cnaes.</p>
</td>
<td>
<p>Number</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>size =  6 or 7.</p>
</td>
</tr>
<tr>
<td>
<p><strong>mainPhone</strong></p>
</td>
<td>
<p>Main phone details.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>phones</strong></p>
</td>
<td>
<p>Additional phones details.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>No</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>mainAddress</strong></p>
</td>
<td>
<p>Main address details.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>adresses</strong></p>
</td>
<td>
<p>Additional addresses details.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>No</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>partners</strong></p>
</td>
<td>
<p>Partners details.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>productSettings</strong></p>
</td>
<td>
<p>Product settings details.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
</tbody>
</table>
<p> </p>



<h2>OBJECT: mainPhone<h2>
<table>
<tbody>
<tr>
<td>
<p><strong>PARAMETER</strong></p>
</td>
<td>
<p><strong>DESCRIPTION</strong></p>
</td>
<td>
<p><strong>VALUE</strong></p>
</td>
<td>
<p><strong>REQUIRED</strong></p>
</td>
<td>
<p><strong>RESTRICTIONS</strong></p>
</td>
</tr>
<tr>
<td>
<p><strong>countryCode</strong></p>
</td>
<td>
<p>Country code number.</p>
</td>
<td>
<p>Number</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>value = 55.</p>
</td>
</tr>
<tr>
<td>
<p><strong>area</strong></p>
</td>
<td>
<p>Area code number.</p>
</td>
<td>
<p>Number</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>size = 2.</p>
</td>
</tr>
<tr>
<td>
<p><strong>number</strong></p>
</td>
<td>
<p>Phone number.</p>
</td>
<td>
<p>Number</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>size = 8 or 9.</p>
</td>
</tr>
<tr>
<td>
<p><strong>type</strong></p>
</td>
<td>
<p>Phone type.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>MOBILE or LANDLINE.</p>
</td>
</tr>
</tbody>
</table>

<p> </p>
<h2>OBJECT: phones<h2>
Same parameters as Object: mainPhone.

<p> </p>
<h2>OBJECT: mainAddress<h2>
<table>
<tbody>
<tr>
<td>
<p><strong>PARAMETER</strong></p>
</td>
<td>
<p><strong>DESCRIPTION</strong></p>
</td>
<td>
<p><strong>VALUE</strong></p>
</td>
<td>
<p><strong>REQUIRED</strong></p>
</td>
<td>
<p><strong>RESTRICTIONS</strong></p>
</td>
</tr>
<tr>
<td>
<p><strong>street</strong></p>
</td>
<td>
<p>Street name.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>max size = 235.</p>
</td>
</tr>
<tr>
<td>
<p><strong>number</strong></p>
</td>
<td>
<p>Address number.</p>
</td>
<td>
<p>Number</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>value &gt; 0.</p>
</td>
</tr>
<tr>
<td>
<p><strong>complement</strong></p>
</td>
<td>
<p>Address complement.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>zip</strong></p>
</td>
<td>
<p>Zip-code.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>size = 8.</p>
</td>
</tr>
<tr>
<td>
<p><strong>neighborhood</strong></p>
</td>
<td>
<p>Neighborhood name.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>city</strong></p>
</td>
<td>
<p>City name.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>state</strong></p>
</td>
<td>
<p>State name.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>size = 2.</p>
</td>
</tr>
<tr>
<td>
<p><strong>country</strong></p>
</td>
<td>
<p>Country name.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>value = Brasil.</p>
</td>
</tr>
</tbody>
</table>

<p> </p>
<h2>OBJECT: addresses<h2>
Same parameters as index 4.3.3. Object: mainAddress.

<p> </p>
<h2>OBJECT: partners</h2>
<table>
<tbody>
<tr>
<td>
<p><strong>PARAMETER</strong></p>
</td>
<td>
<p><strong>DESCRIPTION</strong></p>
</td>
<td>
<p><strong>VALUE</strong></p>
</td>
<td>
<p><strong>REQUIRED</strong></p>
</td>
<td>
<p><strong>RESTRICTIONS</strong></p>
</td>
</tr>
<tr>
<td>
<p><strong>individuals</strong></p>
</td>
<td>
<p>Partner details (natural people).</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>companies</strong></p>
</td>
<td>
<p>Partner details (legal perople).</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>No</p>
</td>
<td> </td>
</tr>
</tbody>
</table>

<p> </p>
<h2>OBJECT: individuals<h2>
<table>
<tbody>
<tr>
<td>
<p><strong>PARAMETER</strong></p>
</td>
<td>
<p><strong>DESCRIPTION</strong></p>
</td>
<td>
<p><strong>VALUE</strong></p>
</td>
<td>
<p><strong>REQUIRED</strong></p>
</td>
<td>
<p><strong>RESTRICTIONS</strong></p>
</td>
</tr>
<tr>
<td>
<p><strong>profile</strong></p>
</td>
<td>
<p>Hierarchical level.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>[OWNER, ATTORNEY]</p>
</td>
</tr>
<tr>
<td>
<p><strong>type</strong></p>
</td>
<td>
<p>Profile type.</p>
</td>
<td>
<p>Array</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>[MASTER]</p>
</td>
</tr>
<tr>
<td>
<p><strong>name</strong></p>
</td>
<td>
<p>Partner name.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>alphabetical; max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>birthDate</strong></p>
</td>
<td>
<p>Partner birth date.</p>
</td>
<td>
<p>Date</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>Date in the past; ISO 8601 format.</p>
</td>
</tr>
<tr>
<td>
<p><strong>motherName</strong></p>
</td>
<td>
<p>Partner mother’s name.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>alphabetical; max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>gender</strong></p>
</td>
<td>
<p>Partner gender.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>[MALE, FEMALE, OTHER, NOT SPECIFIED].</p>
</td>
</tr>
<tr>
<td>
<p><strong>maritalStatus</strong></p>
</td>
<td>
<p>Partner marital status.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>[SINGLE, MARRIED, DIVORCED, WIDOWER]</p>
</td>
</tr>
<tr>
<td>
<p><strong>email</strong></p>
</td>
<td>
<p>Partner mail address.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>occupation</strong></p>
</td>
<td>
<p>Partner occupation.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>isPep</strong></p>
</td>
<td>
<p>Politically exposed person.</p>
</td>
<td>
<p>Boolean</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>[YES, NO].</p>
</td>
</tr>
<tr>
<td>
<p><strong>revenue</strong></p>
</td>
<td>
<p>Partner annual revenue.</p>
</td>
<td>
<p>Number</p>
</td>
<td>
<p>No</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>nationalRegistration</strong></p>
</td>
<td>
<p>Partner national registration ID.</p>
</td>
<td>
<p>Number</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>size = 11.</p>
</td>
</tr>
<tr>
<td>
<p><strong>identityCard</strong></p>
</td>
<td>
<p>State registration details.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>No</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>mainPhone</strong></p>
</td>
<td>
<p>Partner main phone number.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>phones</strong></p>
</td>
<td>
<p>Partner additional phone numbers.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>No</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>mainAddress</strong></p>
</td>
<td>
<p>Partner main address.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>addresses</strong></p>
</td>
<td>
<p>Partner additional addresses.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>No</p>
</td>
<td> </td>
</tr>
</tbody>
</table>

<p> </p>
<h2>OBJECT: identityCard</h2>
<table>
<tbody>
<tr>
<td>
<p><strong>PARAMETER</strong></p>
</td>
<td>
<p><strong>DESCRIPTION</strong></p>
</td>
<td>
<p><strong>VALUE</strong></p>
</td>
<td>
<p><strong>REQUIRED</strong></p>
</td>
<td>
<p><strong>RESTRICTIONS</strong></p>
</td>
</tr>
<tr>
<td>
<p><strong>number</strong></p>
</td>
<td> </td>
<td>
<p>Number</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>size = 7.</p>
</td>
</tr>
<tr>
<td>
<p><strong>dispatcher</strong></p>
</td>
<td> </td>
<td>
<p>String</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>federativeUnit</strong></p>
</td>
<td> </td>
<td>
<p>String</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>size = 2.</p>
</td>
</tr>
<tr>
<td>
<p><strong>emissionDate</strong></p>
</td>
<td> </td>
<td>
<p>Date</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>Date in the past; ISO 8601 format.</p>
</td>
</tr>
</tbody>
</table>

<p> </p>
<h2>OBJECT: companies<h2>
<table>
<tbody>
<tr>
<td>
<p><strong>Parameter</strong></p>
</td>
<td>
<p><strong>Description</strong></p>
</td>
<td>
<p><strong>Value</strong></p>
</td>
<td>
<p><strong>Required</strong></p>
</td>
<td>
<p><strong>Restrictions</strong></p>
</td>
</tr>
<tr>
<td>
<p><strong> company</strong></p>
</td>
<td>
<p>Company details.</p>
</td>
<td>
<p>Array</p>
</td>
<td> </td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>nationalRegistration</strong></p>
</td>
<td>
<p>Company national registration (CNPJ).</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>size = 14.</p>
</td>
</tr>
<tr>
<td>
<p><strong>legalName</strong></p>
</td>
<td>
<p>Company legal name.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>legalNature</strong></p>
</td>
<td>
<p>Company legal nature.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>size = 4.</p>
</td>
</tr>
<tr>
<td>
<p><strong>legalStatus</strong></p>
</td>
<td>
<p>Company legal status.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>tradeName</strong></p>
</td>
<td>
<p>Company trade name.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>max size = 255.</p>
</td>
</tr>
<tr>
<td>
<p><strong>establishmentDate</strong></p>
</td>
<td>
<p>Company foundation date.</p>
</td>
<td>
<p>Date</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>Date in the past; ISO 8601 format.</p>
</td>
</tr>
<tr>
<td>
<p><strong>establishmentFormat</strong></p>
</td>
<td>
<p>Company establishment format.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>[EI, MEI, EIRELI, LTDA, SS, SA, ME, EPP, EMGP].</p>
</td>
</tr>
<tr>
<td>
<p><strong>stateRegistration</strong></p>
</td>
<td>
<p>Company state registration.</p>
</td>
<td>
<p>Integer</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>max size = 16.</p>
</td>
</tr>
<tr>
<td>
<p><strong>email</strong></p>
</td>
<td>
<p>Company mail address.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>revenue</strong></p>
</td>
<td>
<p>Company annual revenue.</p>
</td>
<td>
<p>Double </p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>default: 0.0.</p>
</td>
</tr>
<tr>
<td>
<p><strong>mainCnae</strong></p>
</td>
<td>
<p>Main cnae.</p>
</td>
<td>
<p>Number</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>size =  6 or 7.</p>
</td>
</tr>
</tbody>
</table>
<table>


<p> </p>
<h2>OBJECT: productSettings<h2>
<table>
<tbody>
<tr>
<td>
<p><strong>PARAMETER</strong></p>
</td>
<td>
<p><strong>DESCRIPTION</strong></p>
</td>
<td>
<p><strong>VALUE</strong></p>
</td>
<td>
<p><strong>REQUIRED</strong></p>
</td>
<td>
<p><strong>RESTRICTIONS</strong></p>
</td>
</tr>
<tr>
<td>
<p><strong>idProduct</strong></p>
</td>
<td>
<p>Company product ID.</p>
</td>
<td>
<p>Number</p>
</td>
<td>
<p>Yes</p>
</td>
<td>
<p>size = 1.</p>
</td>
</tr>
<tr>
<td>
<p><strong>externalAccountNumber</strong></p>
</td>
<td>
<p>External authorization.</p>
</td>
<td>
<p>String</p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>max size = 16.</p>
</td>
</tr>
<tr>
<td>
<p><strong>termsAndConditionsTokens</strong></p>
</td>
<td>
<p>Terms and conditions tokens details.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
<tr>
<td>
<p><strong>deviceIdentification</strong></p>
</td>
<td>
<p>Device identification details.</p>
</td>
<td>
<p>Object</p>
</td>
<td>
<p>Yes</p>
</td>
<td> </td>
</tr>
</tbody>
</table></h2></h2></table></h2></h2></h2></h2></h2></h2></h2></h2></h2></h2></h2></h2></h2></h2>
     */
    it("should testMRegistrations response", function testMRegistrationsTest(done) {
        // parameters for the API call
        let authorization = '{{tokenOauth}}';
        let contentType = 'application/json';
        let body = baseController.getObjectMapper().mapObject({
  "company": {
    "nationalRegistration": "04707118000105",
    "legalName": "CORPORATION LTDA UPDATED",
    "legalNature": "3999",
    "legalStatus": "ATIVO",
    "tradeName": "DV CORP BRASIL",
    "establishmentDate": "1959-05-12",
    "establishmentFormat": "ME",
    "stateRegistration": "12345678",
    "email": "contato@dvcorp.com.br",
    "revenue": 201,
    "partnerChangeInLastTwelveMonths": false,
    "mainCnae": "9329803",
    "cnaes": [
      "0111301",
      "0111302"
    ],
    "mainPhone": {
      "countryCode": "55",
      "area": "11",
      "number": "978789564",
      "type": "MOBILE"
    },
    "phones": [
      {
        "countryCode": "55",
        "area": "11",
        "number": "978789564",
        "type": "MOBILE"
      }
    ],
    "mainAddress": {
      "street": "RUA MARIA JESUS",
      "number": "865",
      "complement": "A",
      "zip": "02678070",
      "neighborhood": "OSASCO",
      "city": "SALVADOR",
      "state": "SP",
      "country": "BRASIL"
    },
    "addresses": [
      {
        "street": "RUA MARIA JESUS",
        "number": "865",
        "complement": "A",
        "zip": "02678070",
        "neighborhood": "OSASCO",
        "city": "ARARAQUARA",
        "state": "SP",
        "country": "BRAZIL"
      }
    ],
    "partners": {
      "individuals": [
        {
          "isPep": false,
          "profile": "ATTORNEY",
          "type": [
            "MASTER"
          ],
          "name": "JOAQUINA SANTOS SALES",
          "birthDate": "1993-10-05",
          "motherName": "MARIA LUIZA SANTOS SALES",
          "gender": "MALE",
          "maritalStatus": "SINGLE",
          "email": "teste@teste.com.br",
          "occupation": "ARQUITETO",
          "pep": true,
          "revenue": 201,
          "nationalRegistration": "38768069847",
          "identityCard": {
            "number": "5874589",
            "dispatcher": "SSP",
            "federativeUnit": "SP",
            "emissionDate": "1993-10-05"
          },
          "mainPhone": {
            "countryCode": "55",
            "area": "11",
            "number": "978789564",
            "type": "LANDLINE"
          },
          "phones": [
            {
              "countryCode": "55",
              "area": "11",
              "number": "978789564",
              "type": "LANDLINE"
            }
          ],
          "mainAddress": {
            "street": "RUA MARIA JESUS",
            "number": "865",
            "complement": "A",
            "zip": "02678070",
            "neighborhood": "OSASCO",
            "city": "SÃO PAULO",
            "state": "SP",
            "country": "BRASIL"
          },
          "addresses": [
            {
              "type": "STREET",
              "street": "RUA MARIA JESUS",
              "number": "865",
              "complement": "A",
              "zip": "02678070",
              "neighborhood": "OSASCO",
              "city": "SÃO PAULO",
              "state": "SP",
              "country": "BRASIL"
            }
          ],
          "birthdate": null
        }
      ],
      "companies": [
        {
          "nationalRegistration": "29896444000139",
          "legalName": "DURVAL MATIAS CORPORATION LTDA",
          "legalNature": "3999",
          "legalStatus": "ATIVO",
          "tradeName": "DV CORP BRASIL",
          "establishmentDate": "1959-05-12",
          "establishmentFormat": "EI",
          "stateRegistration": "76876876",
          "email": "contato@dvcorp.com.br",
          "revenue": 201,
          "partnerChangeInLastTwelveMonths": false,
          "mainCnae": "0111301",
          "cnaes": [
            "0111301",
            "0111302"
          ],
          "mainPhone": {
            "countryCode": "55",
            "area": "11",
            "number": "978789564",
            "type": "LANDLINE"
          },
          "phones": [
            {
              "countryCode": "55",
              "area": "11",
              "number": "978789564",
              "type": "MOBILE"
            }
          ],
          "mainAddress": {
            "street": "RUA MARIA JESUS",
            "number": "865",
            "complement": "A",
            "zip": "02678070",
            "neighborhood": "OSASCO",
            "city": "SÃO PAULO",
            "state": "SP",
            "country": "BRASIL"
          },
          "addresses": [
            {
              "street": "RUA MARIA JESUS",
              "number": "865",
              "complement": "A",
              "zip": "02678070",
              "neighborhood": "OSASCO",
              "city": "SÃO PAULO",
              "state": "SP",
              "country": "BRAZIL"
            }
          ]
        }
      ]
    }
  },
  "productSettings": {
    "printedCardName": "DURVAL MATIAS CORPORATION",
    "externalAccountNumber": "99999X",
    "termsAndConditionsTokens": [
      "c58f4b15-1947-4b80-ae65-fc3ec429f763",
      "926e5f8c-7743-4b5c-9d6d-cecbb4f02d6b"
    ],
    "deviceIdentification": {
      "fingerprint": "AABCCDDDEEF#698931226"
    }
  }
}, 'MRegistrationsrequest');

        controller.createRegistrations(authorization, contentType, body, function callback(error, response, context) {
            // test response code
            assert.equal(201, context.response.statusCode);
            // test headers
            let headers = [];
            headers['Date'] = null;
            headers['Content-Type'] = null;
            headers['Content-Length'] = null;
            headers['Connection'] = null;
            headers['x-amzn-RequestId'] = null;
            headers['x-amzn-Remapped-Content-Length'] = null;
            headers['x-amz-apigw-id'] = null;
            headers['X-Amzn-Trace-Id'] = null;
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            assert.isNotNull(response);
            assert.isTrue(TestHelper.isProperSubsetOf(context.response.body, {
  "message": "Waiting documents",
  "result": {
    "registrationId": "791d1dbe-f6cd-48cd-a21b-dce0dbd83201"
  }
}, false, true, false));
            done();
        }).catch(() => undefined);
    });

    /**
     * TODO: Add Description
     */
    it("should testMRegistrationsRegistrationId response", function testMRegistrationsRegistrationIdTest(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let authorization = '{{tokenOauth}}';
        let body = baseController.getObjectMapper().mapObject({
  "company": {
    "nationalRegistration": "04707118000105",
    "legalName": "CORPORATION LTDA UPDATED",
    "legalNature": "3999",
    "legalStatus": "ATIVO",
    "tradeName": "DV CORP BRASIL",
    "establishmentDate": "1959-05-12",
    "establishmentFormat": "ME",
    "stateRegistration": "12345678",
    "email": "contato@dvcorp.com.br",
    "revenue": 201,
    "partnerChangeInLastTwelveMonths": false,
    "mainCnae": "9329803",
    "cnaes": [
      "0111301",
      "0111302"
    ],
    "mainPhone": {
      "countryCode": "55",
      "area": "11",
      "number": "978789564",
      "type": "MOBILE"
    },
    "phones": [
      {
        "countryCode": "55",
        "area": "11",
        "number": "978789564",
        "type": "MOBILE"
      }
    ],
    "mainAddress": {
      "street": "RUA MARIA JESUS",
      "number": "865",
      "complement": "A",
      "zip": "02678070",
      "neighborhood": "OSASCO",
      "city": "SALVADOR",
      "state": "SP",
      "country": "BRASIL"
    },
    "addresses": [
      {
        "street": "RUA MARIA JESUS",
        "number": "865",
        "complement": "A",
        "zip": "02678070",
        "neighborhood": "OSASCO",
        "city": "ARARAQUARA",
        "state": "SP",
        "country": "BRAZIL"
      }
    ],
    "partners": {
      "individuals": [
        {
          "isPep": false,
          "profile": "ATTORNEY",
          "type": [
            "MASTER"
          ],
          "name": "JOAQUINA SANTOS SALES",
          "birthDate": "1993-10-05",
          "motherName": "MARIA LUIZA SANTOS SALES",
          "gender": "MALE",
          "maritalStatus": "SINGLE",
          "email": "teste@teste.com.br",
          "occupation": "ARQUITETO",
          "pep": true,
          "revenue": 201,
          "nationalRegistration": "38768069847",
          "identityCard": {
            "number": "5874589",
            "dispatcher": "SSP",
            "federativeUnit": "SP",
            "emissionDate": "1993-10-05"
          },
          "mainPhone": {
            "countryCode": "55",
            "area": "11",
            "number": "978789564",
            "type": "LANDLINE"
          },
          "phones": [
            {
              "countryCode": "55",
              "area": "11",
              "number": "978789564",
              "type": "LANDLINE"
            }
          ],
          "mainAddress": {
            "street": "RUA MARIA JESUS",
            "number": "865",
            "complement": "A",
            "zip": "02678070",
            "neighborhood": "OSASCO",
            "city": "SÃO PAULO",
            "state": "SP",
            "country": "BRASIL"
          },
          "addresses": [
            {
              "type": "STREET",
              "street": "RUA MARIA JESUS",
              "number": "865",
              "complement": "A",
              "zip": "02678070",
              "neighborhood": "OSASCO",
              "city": "SÃO PAULO",
              "state": "SP",
              "country": "BRASIL"
            }
          ],
          "birthdate": null
        }
      ],
      "companies": [
        {
          "nationalRegistration": "29896444000139",
          "legalName": "DURVAL MATIAS CORPORATION LTDA",
          "legalNature": "3999",
          "legalStatus": "ATIVO",
          "tradeName": "DV CORP BRASIL",
          "establishmentDate": "1959-05-12",
          "establishmentFormat": "EI",
          "stateRegistration": "76876876",
          "email": "contato@dvcorp.com.br",
          "revenue": 201,
          "partnerChangeInLastTwelveMonths": false,
          "mainCnae": "0111301",
          "cnaes": [
            "0111301",
            "0111302"
          ],
          "mainPhone": {
            "countryCode": "55",
            "area": "11",
            "number": "978789564",
            "type": "LANDLINE"
          },
          "phones": [
            {
              "countryCode": "55",
              "area": "11",
              "number": "978789564",
              "type": "MOBILE"
            }
          ],
          "mainAddress": {
            "street": "RUA MARIA JESUS",
            "number": "865",
            "complement": "A",
            "zip": "02678070",
            "neighborhood": "OSASCO",
            "city": "SÃO PAULO",
            "state": "SP",
            "country": "BRASIL"
          },
          "addresses": [
            {
              "street": "RUA MARIA JESUS",
              "number": "865",
              "complement": "A",
              "zip": "02678070",
              "neighborhood": "OSASCO",
              "city": "SÃO PAULO",
              "state": "SP",
              "country": "BRAZIL"
            }
          ]
        }
      ]
    }
  },
  "productSettings": {
    "printedCardName": "DURVAL MATIAS CORPORATION",
    "externalAccountNumber": "99999X",
    "termsAndConditionsTokens": [
      "c58f4b15-1947-4b80-ae65-fc3ec429f763",
      "926e5f8c-7743-4b5c-9d6d-cecbb4f02d6b"
    ],
    "deviceIdentification": {
      "fingerprint": "AABCCDDDEEF#698931226"
    }
  }
}, 'MRegistrationsRegistrationIdRequest');

        controller.updateRegistrationsRegistrationId(contentType, authorization, body, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            // test headers
            let headers = [];
            headers['Date'] = null;
            headers['Content-Type'] = null;
            headers['Content-Length'] = null;
            headers['Connection'] = null;
            headers['x-amzn-RequestId'] = null;
            headers['x-amzn-Remapped-Content-Length'] = null;
            headers['x-amz-apigw-id'] = null;
            headers['X-Amzn-Trace-Id'] = null;
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            assert.isNotNull(response);
            assert.isTrue(TestHelper.isProperSubsetOf(context.response.body, {
  "message": "Update success"
}, false, true, false));
            done();
        }).catch(() => undefined);
    });

    /**
     * TODO: Add Description
     */
    it("should testMRegisteredCompaniesCompanyId response", function testMRegisteredCompaniesCompanyIdTest(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let authorization = '{{tokenOauth}}';
        let body = baseController.getObjectMapper().mapObject({
  "company": {
    "nationalRegistration": "04707118000105",
    "legalName": "CORPORATION LTDA UPDATED",
    "legalNature": "3999",
    "legalStatus": "ATIVO",
    "tradeName": "DV CORP BRASIL",
    "establishmentDate": "1959-05-12",
    "establishmentFormat": "ME",
    "stateRegistration": "12345678",
    "email": "contato@dvcorp.com.br",
    "revenue": 201,
    "partnerChangeInLastTwelveMonths": false,
    "mainCnae": "9329803",
    "cnaes": [
      "0111301",
      "0111302"
    ],
    "mainPhone": {
      "countryCode": "55",
      "area": "11",
      "number": "978789564",
      "type": "MOBILE"
    },
    "phones": [
      {
        "countryCode": "55",
        "area": "11",
        "number": "978789564",
        "type": "MOBILE"
      }
    ],
    "mainAddress": {
      "street": "RUA MARIA JESUS",
      "number": "865",
      "complement": "A",
      "zip": "02678070",
      "neighborhood": "OSASCO",
      "city": "SALVADOR",
      "state": "SP",
      "country": "BRASIL"
    },
    "addresses": [
      {
        "street": "RUA MARIA JESUS",
        "number": "865",
        "complement": "A",
        "zip": "02678070",
        "neighborhood": "OSASCO",
        "city": "ARARAQUARA",
        "state": "SP",
        "country": "BRAZIL"
      }
    ],
    "partners": {
      "individuals": [
        {
          "isPep": false,
          "profile": "ATTORNEY",
          "type": [
            "MASTER"
          ],
          "name": "JOAQUINA SANTOS SALES",
          "birthDate": "1993-10-05",
          "motherName": "MARIA LUIZA SANTOS SALES",
          "gender": "MALE",
          "maritalStatus": "SINGLE",
          "email": "teste@teste.com.br",
          "occupation": "ARQUITETO",
          "pep": true,
          "revenue": 201,
          "nationalRegistration": "38768069847",
          "identityCard": {
            "number": "5874589",
            "dispatcher": "SSP",
            "federativeUnit": "SP",
            "emissionDate": "1993-10-05"
          },
          "mainPhone": {
            "countryCode": "55",
            "area": "11",
            "number": "978789564",
            "type": "LANDLINE"
          },
          "phones": [
            {
              "countryCode": "55",
              "area": "11",
              "number": "978789564",
              "type": "LANDLINE"
            }
          ],
          "mainAddress": {
            "street": "RUA MARIA JESUS",
            "number": "865",
            "complement": "A",
            "zip": "02678070",
            "neighborhood": "OSASCO",
            "city": "SÃO PAULO",
            "state": "SP",
            "country": "BRASIL"
          },
          "addresses": [
            {
              "type": "STREET",
              "street": "RUA MARIA JESUS",
              "number": "865",
              "complement": "A",
              "zip": "02678070",
              "neighborhood": "OSASCO",
              "city": "SÃO PAULO",
              "state": "SP",
              "country": "BRASIL"
            }
          ],
          "birthdate": null
        }
      ],
      "companies": [
        {
          "nationalRegistration": "29896444000139",
          "legalName": "DURVAL MATIAS CORPORATION LTDA",
          "legalNature": "3999",
          "legalStatus": "ATIVO",
          "tradeName": "DV CORP BRASIL",
          "establishmentDate": "1959-05-12",
          "establishmentFormat": "EI",
          "stateRegistration": "76876876",
          "email": "contato@dvcorp.com.br",
          "revenue": 201,
          "partnerChangeInLastTwelveMonths": false,
          "mainCnae": "0111301",
          "cnaes": [
            "0111301",
            "0111302"
          ],
          "mainPhone": {
            "countryCode": "55",
            "area": "11",
            "number": "978789564",
            "type": "LANDLINE"
          },
          "phones": [
            {
              "countryCode": "55",
              "area": "11",
              "number": "978789564",
              "type": "MOBILE"
            }
          ],
          "mainAddress": {
            "street": "RUA MARIA JESUS",
            "number": "865",
            "complement": "A",
            "zip": "02678070",
            "neighborhood": "OSASCO",
            "city": "SÃO PAULO",
            "state": "SP",
            "country": "BRASIL"
          },
          "addresses": [
            {
              "street": "RUA MARIA JESUS",
              "number": "865",
              "complement": "A",
              "zip": "02678070",
              "neighborhood": "OSASCO",
              "city": "SÃO PAULO",
              "state": "SP",
              "country": "BRAZIL"
            }
          ]
        }
      ]
    }
  },
  "productSettings": {
    "printedCardName": "DURVAL MATIAS CORPORATION",
    "externalAccountNumber": "99999X",
    "termsAndConditionsTokens": [
      "c58f4b15-1947-4b80-ae65-fc3ec429f763",
      "926e5f8c-7743-4b5c-9d6d-cecbb4f02d6b"
    ],
    "deviceIdentification": {
      "fingerprint": "AABCCDDDEEF#698931226"
    }
  }
}, 'MRegisteredCompaniesCompanyIdRequest');

        controller.updateRegisteredCompaniesCompanyId(contentType, authorization, body, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            // test headers
            let headers = [];
            headers['Date'] = null;
            headers['Content-Type'] = null;
            headers['Content-Length'] = null;
            headers['Connection'] = null;
            headers['x-amzn-RequestId'] = null;
            headers['x-amzn-Remapped-Content-Length'] = null;
            headers['x-amz-apigw-id'] = null;
            headers['X-Amzn-Trace-Id'] = null;
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            assert.isNotNull(response);
            assert.isTrue(TestHelper.isProperSubsetOf(context.response.body, {
  "message": "Update Success.",
  "result": {
    "registrationId": "791d1dbe-f6cd-48cd-a21b-dce0dbd83201"
  }
}, false, true, false));
            done();
        }).catch(() => undefined);
    });
    /**
     * TODO: Add Description
     */
    it("should testMRegistrationsRegistrationId1 response", function testMRegistrationsRegistrationId1Test(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let authorization = '{{tokenOauth}}';

        controller.getRegistrationsRegistrationId(contentType, authorization, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            // test headers
            let headers = [];
            headers['Date'] = null;
            headers['Content-Type'] = null;
            headers['Content-Length'] = null;
            headers['Connection'] = null;
            headers['x-amzn-RequestId'] = null;
            headers['x-amzn-Remapped-Content-Length'] = null;
            headers['x-amz-apigw-id'] = null;
            headers['X-Amzn-Trace-Id'] = null;
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            assert.isNotNull(response);
            assert.isTrue(TestHelper.isProperSubsetOf(context.response.body, {
  "message": "Result found.",
  "result": {
    "company": {
      "stateRegistration": "12345678",
      "partnerChangeInLastTwelveMonths": false,
      "cnaes": [
        "0111301",
        "0111302"
      ],
      "addresses": [
        {
          "zip": "02678070",
          "number": "865",
          "country": "BRAZIL",
          "city": "ARARAQUARA",
          "street": "RUA MARIA JESUS",
          "neighborhood": "OSASCO",
          "state": "SP",
          "complement": "A"
        }
      ],
      "establishmentDate": "1959-05-12",
      "mainPhone": {
        "area": "11",
        "number": "978789564",
        "type": "MOBILE",
        "countryCode": "55"
      },
      "legalStatus": "ATIVO",
      "phones": [
        {
          "area": "11",
          "number": "978789564",
          "type": "MOBILE",
          "countryCode": "55"
        }
      ],
      "mainAddress": {
        "zip": "02678070",
        "number": "865",
        "country": "BRASIL",
        "city": "SALVADOR",
        "street": "RUA MARIA JESUS",
        "neighborhood": "OSASCO",
        "state": "SP",
        "complement": "A"
      },
      "nationalRegistration": "04707118000105",
      "establishmentFormat": "ME",
      "legalName": "CORPORATION LTDA UPDATED",
      "tradeName": "DV CORP BRASIL",
      "revenue": 201,
      "partners": {
        "individuals": [
          {
            "addresses": [
              {
                "zip": "02678070",
                "number": "865",
                "country": "BRASIL",
                "city": "SÃO PAULO",
                "street": "RUA MARIA JESUS",
                "neighborhood": "OSASCO",
                "state": "SP",
                "type": "STREET",
                "complement": "A"
              }
            ],
            "occupation": "ARQUITETO",
            "birthdate": null,
            "gender": "MALE",
            "mainPhone": {
              "area": "11",
              "number": "978789564",
              "type": "LANDLINE",
              "countryCode": "55"
            },
            "profile": "ATTORNEY",
            "motherName": "MARIA LUIZA SANTOS SALES",
            "phones": [
              {
                "area": "11",
                "number": "978789564",
                "type": "LANDLINE",
                "countryCode": "55"
              }
            ],
            "identityCard": {
              "number": "5874589",
              "federativeUnit": "SP",
              "emissionDate": "1993-10-05",
              "dispatcher": "SSP"
            },
            "isPep": false,
            "type": [
              "MASTER"
            ],
            "birthDate": "1993-10-05",
            "mainAddress": {
              "zip": "02678070",
              "number": "865",
              "country": "BRASIL",
              "city": "SÃO PAULO",
              "street": "RUA MARIA JESUS",
              "neighborhood": "OSASCO",
              "state": "SP",
              "complement": "A"
            },
            "nationalRegistration": "38768069847",
            "revenue": 201,
            "name": "JOAQUINA SANTOS SALES",
            "pep": true,
            "maritalStatus": "SINGLE",
            "email": "teste@teste.com.br"
          }
        ],
        "companies": [
          {
            "stateRegistration": "76876876",
            "partnerChangeInLastTwelveMonths": false,
            "cnaes": [
              "0111301",
              "0111302"
            ],
            "addresses": [
              {
                "zip": "02678070",
                "number": "865",
                "country": "BRAZIL",
                "city": "SÃO PAULO",
                "street": "RUA MARIA JESUS",
                "neighborhood": "OSASCO",
                "state": "SP",
                "complement": "A"
              }
            ],
            "establishmentDate": "1959-05-12",
            "mainPhone": {
              "area": "11",
              "number": "978789564",
              "type": "LANDLINE",
              "countryCode": "55"
            },
            "legalStatus": "ATIVO",
            "phones": [
              {
                "area": "11",
                "number": "978789564",
                "type": "MOBILE",
                "countryCode": "55"
              }
            ],
            "mainAddress": {
              "zip": "02678070",
              "number": "865",
              "country": "BRASIL",
              "city": "SÃO PAULO",
              "street": "RUA MARIA JESUS",
              "neighborhood": "OSASCO",
              "state": "SP",
              "complement": "A"
            },
            "nationalRegistration": "29896444000139",
            "establishmentFormat": "EI",
            "legalName": "DURVAL MATIAS CORPORATION LTDA",
            "tradeName": "DV CORP BRASIL",
            "revenue": 201,
            "legalNature": "3999",
            "email": "contato@dvcorp.com.br",
            "mainCnae": "0111301"
          }
        ]
      },
      "legalNature": "3999",
      "email": "contato@dvcorp.com.br",
      "mainCnae": "9329803"
    },
    "productSettings": {
      "termsAndConditionsTokens": [
        "c58f4b15-1947-4b80-ae65-fc3ec429f763",
        "926e5f8c-7743-4b5c-9d6d-cecbb4f02d6b"
      ],
      "printedCardName": "DURVAL MATIAS CORPORATION",
      "externalAccountNumber": "99999X",
      "deviceIdentification": {
        "fingerprint": "AABCCDDDEEF#698931226"
      }
    }
  }
}, false, true, false));
            done();
        }).catch(() => undefined);
    });

    /**
     * TODO: Add Description
     */
    it("should testMRegistrationsRegistrationIdDocuments response", function testMRegistrationsRegistrationIdDocumentsTest(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let authorization = '{{tokenOauth}}';

        controller.getRegistrationsRegistrationIdDocuments(contentType, authorization, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            // test headers
            let headers = [];
            headers['Date'] = null;
            headers['Content-Type'] = null;
            headers['Content-Length'] = null;
            headers['Connection'] = null;
            headers['x-amzn-RequestId'] = null;
            headers['x-amzn-Remapped-Content-Length'] = null;
            headers['x-amz-apigw-id'] = null;
            headers['X-Amzn-Trace-Id'] = null;
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            assert.isNotNull(response);
            assert.isTrue(TestHelper.isProperSubsetOf(context.response.body, {
  "message": "Result found.",
  "result": [
    {
      "documentId": "18c99ff0-3b2b-4580-bdd5-11f33df5399e",
      "documentType": "ARTICLES_OF_ASSOCIATION",
      "url": "https: //docspy-hml.s3.amazonaws.com/documents/103/ID_COMPANY-c6f09995-af8c-4e0f-89f4-1beca1da7b5f-CATEGORY-3-TIMESTAMP-1573150361.367251.pdf",
      "created": "2019-11-07T18: 12: 41.861548"
    }
  ]
}, false, true, false));
            done();
        }).catch(() => undefined);
    });

    /**
     * TODO: Add Description
     */
    it("should testMRegistrationsCompaniesCNPJPartnersCPF response", function testMRegistrationsCompaniesCNPJPartnersCPFTest(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let authorization = '{{tokenOauth}}';

        controller.getRegistrationsCompaniesCNPJPartnersCPF(contentType, authorization, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            // test headers
            let headers = [];
            headers['Date'] = null;
            headers['Content-Type'] = null;
            headers['Content-Length'] = null;
            headers['Connection'] = null;
            headers['x-amzn-RequestId'] = null;
            headers['x-amzn-Remapped-Content-Length'] = null;
            headers['x-amz-apigw-id'] = null;
            headers['X-Amzn-Trace-Id'] = null;
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            assert.isNotNull(response);
            assert.isTrue(TestHelper.isProperSubsetOf(context.response.body, {
  "message": "Result found.",
  "result": {
    "partner": {
      "addresses": [
        {
          "zip": "02678070",
          "number": "865",
          "country": "BRASIL",
          "city": "SÃO PAULO",
          "street": "RUA MARIA JESUS",
          "neighborhood": "OSASCO",
          "state": "SP",
          "type": "STREET",
          "complement": "A"
        }
      ],
      "occupation": "ARQUITETO",
      "gender": "MALE",
      "mainPhone": {
        "area": "11",
        "number": "123456789",
        "type": "LANDLINE",
        "countryCode": "55"
      },
      "profile": "ATTORNEY",
      "motherName": "MARIA LUIZA SANTOS SALES",
      "phones": [
        {
          "area": "11",
          "number": "978789564",
          "type": "LANDLINE",
          "countryCode": "55"
        }
      ],
      "identityCard": {
        "number": "5874589",
        "federativeUnit": "SP",
        "emissionDate": "1993-10-05",
        "dispatcher": "SSP"
      },
      "isPep": false,
      "type": [
        "MASTER"
      ],
      "birthDate": "1990-12-31",
      "mainAddress": {
        "zip": "02678070",
        "number": "865",
        "country": "BRASIL",
        "city": "SÃO PAULO",
        "street": "RUA MARIA JESUS",
        "neighborhood": "OSASCO",
        "state": "SP",
        "complement": "A"
      },
      "nationalRegistration": "38768069847",
      "revenue": 201,
      "name": "JOAQUINA SANTOS SALES",
      "pep": true,
      "maritalStatus": "WIDOWER",
      "email": "teste@teste.com.br"
    }
  }
}, false, true, false));
            done();
        }).catch(() => undefined);
    });

    /**
     * TODO: Add Description
     */
    it("should testMRegisteredCompaniesCompanyId1 response", function testMRegisteredCompaniesCompanyId1Test(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let authorization = '{{tokenOauth}}';

        controller.getRegisteredCompaniesCompanyId(contentType, authorization, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            // test headers
            let headers = [];
            headers['Date'] = null;
            headers['Content-Type'] = null;
            headers['Content-Length'] = null;
            headers['Connection'] = null;
            headers['x-amzn-RequestId'] = null;
            headers['x-amzn-Remapped-Content-Length'] = null;
            headers['x-amz-apigw-id'] = null;
            headers['X-Amzn-Trace-Id'] = null;
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            assert.isNotNull(response);
            assert.isTrue(TestHelper.isProperSubsetOf(context.response.body, {
  "message": "Found in local database.",
  "result": {
    "company": {
      "stateRegistration": "12345678",
      "partnerChangeInLastTwelveMonths": false,
      "cnaes": [
        "0111301",
        "0111302"
      ],
      "addresses": [
        {
          "zip": "02678070",
          "number": "865",
          "country": "BRAZIL",
          "city": "ARARAQUARA",
          "street": "RUA MARIA JESUS",
          "neighborhood": "OSASCO",
          "state": "SP",
          "complement": "A"
        }
      ],
      "establishmentDate": "1959-05-12",
      "mainPhone": {
        "area": "11",
        "number": "978789564",
        "type": "MOBILE",
        "countryCode": "55"
      },
      "legalStatus": "ATIVO",
      "phones": [
        {
          "area": "11",
          "number": "978789564",
          "type": "MOBILE",
          "countryCode": "55"
        }
      ],
      "mainAddress": {
        "zip": "02678070",
        "number": "865",
        "country": "BRASIL",
        "city": "SALVADOR",
        "street": "RUA MARIA JESUS",
        "neighborhood": "OSASCO",
        "state": "SP",
        "complement": "A"
      },
      "nationalRegistration": "04707118000105",
      "establishmentFormat": "ME",
      "legalName": "CORPORATION LTDA UPDATED",
      "tradeName": "DV CORP BRASIL",
      "revenue": 201,
      "partners": {
        "individuals": [
          {
            "addresses": [
              {
                "zip": "02678070",
                "number": "865",
                "country": "BRASIL",
                "city": "SÃO PAULO",
                "street": "RUA MARIA JESUS",
                "neighborhood": "OSASCO",
                "state": "SP",
                "type": "STREET",
                "complement": "A"
              }
            ],
            "occupation": "ARQUITETO",
            "birthdate": null,
            "gender": "MALE",
            "mainPhone": {
              "area": "11",
              "number": "978789564",
              "type": "LANDLINE",
              "countryCode": "55"
            },
            "profile": "ATTORNEY",
            "motherName": "MARIA LUIZA SANTOS SALES",
            "phones": [
              {
                "area": "11",
                "number": "978789564",
                "type": "LANDLINE",
                "countryCode": "55"
              }
            ],
            "identityCard": {
              "number": "5874589",
              "federativeUnit": "SP",
              "emissionDate": "1993-10-05",
              "dispatcher": "SSP"
            },
            "isPep": false,
            "type": [
              "MASTER"
            ],
            "birthDate": "1993-10-05",
            "mainAddress": {
              "zip": "02678070",
              "number": "865",
              "country": "BRASIL",
              "city": "SÃO PAULO",
              "street": "RUA MARIA JESUS",
              "neighborhood": "OSASCO",
              "state": "SP",
              "complement": "A"
            },
            "nationalRegistration": "38768069847",
            "revenue": 201,
            "name": "JOAQUINA SANTOS SALES",
            "pep": true,
            "maritalStatus": "SINGLE",
            "email": "teste@teste.com.br"
          }
        ],
        "companies": [
          {
            "stateRegistration": "76876876",
            "partnerChangeInLastTwelveMonths": false,
            "cnaes": [
              "0111301",
              "0111302"
            ],
            "addresses": [
              {
                "zip": "02678070",
                "number": "865",
                "country": "BRAZIL",
                "city": "SÃO PAULO",
                "street": "RUA MARIA JESUS",
                "neighborhood": "OSASCO",
                "state": "SP",
                "complement": "A"
              }
            ],
            "establishmentDate": "1959-05-12",
            "mainPhone": {
              "area": "11",
              "number": "978789564",
              "type": "LANDLINE",
              "countryCode": "55"
            },
            "legalStatus": "ATIVO",
            "phones": [
              {
                "area": "11",
                "number": "978789564",
                "type": "MOBILE",
                "countryCode": "55"
              }
            ],
            "mainAddress": {
              "zip": "02678070",
              "number": "865",
              "country": "BRASIL",
              "city": "SÃO PAULO",
              "street": "RUA MARIA JESUS",
              "neighborhood": "OSASCO",
              "state": "SP",
              "complement": "A"
            },
            "nationalRegistration": "29896444000139",
            "establishmentFormat": "EI",
            "legalName": "DURVAL MATIAS CORPORATION LTDA",
            "tradeName": "DV CORP BRASIL",
            "revenue": 201,
            "legalNature": "3999",
            "email": "contato@dvcorp.com.br",
            "mainCnae": "0111301"
          }
        ]
      },
      "legalNature": "3999",
      "email": "contato@dvcorp.com.br",
      "mainCnae": "9329803"
    }
  }
}, false, true, false));
            done();
        }).catch(() => undefined);
    });

});
