/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");
const baseController = require("../../lib/Controllers/BaseController");

const controller = testerlib.VisaOneClickController;
const MOneclickEnrollmentsrequest = testerlib.MOneclickEnrollmentsrequest;

describe("VisaOneClickController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * TODO: Add Description
     */
    it("should testMOneclickCampaigns response", function testMOneclickCampaignsTest(done) {
        // parameters for the API call
        let authorization = '{{tokenOauth}}';
        let accessToken = 'eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6WyJhcGlzK3JhcHBpKzAxMTEyMDIwQGh5cGVyYXRpdmEuY29tLmJyIiwiYXBpcytyYXBwaSswMTExMjAyMEBoeXBlcmF0aXZhLmNvbS5iciJdLCJqdGkiOiI4ZDY4YWU3ZDVjMGU0MzIyYTVlYWIzMWE3M2M1YjRjMyIsImhhbyI6IjVmNWUzY2QzMGY3YmQ5NDhhZjQ3ODBiZmUyNjA1ODBkIiwibmJmIjoxNTc1NDA5NzYyLCJleHAiOjE1NzU0MTAwNjIsImlhdCI6MTU3NTQwOTc2MiwiaXNzIjoiSHlwZXJhdGl2YSBIeXBlclBsYXRhZm9ybWEiLCJhdWQiOiJIeXBlcmF0aXZhIENsaWVudCBBcHBsaWNhdGlvbnMifQ.QEtcul6LRCGX8powUKN1WXhpMIlVFH-huRV8Q_3l4drocQA1OrwZhqH4DsKO0QJkUclJKAZQJa-55l7Ct-xWYw';

        controller.getOneclickCampaigns(authorization, accessToken, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        }).catch(() => undefined);
    });

    /**
     * TODO: Add Description
     */
    it("should testMOneclickEnrollments response", function testMOneclickEnrollmentsTest(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let authorization = '{{tokenOauth}}';
        let accessToken = 'eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6WyJhcGlzK3JhcHBpKzAxMTEyMDIwQGh5cGVyYXRpdmEuY29tLmJyIiwiYXBpcytyYXBwaSswMTExMjAyMEBoeXBlcmF0aXZhLmNvbS5iciJdLCJqdGkiOiIyZjdjY2IyMjk4NTA0NjQyOGJjNTJlOTE2NTk0NzBjMSIsImhhbyI6Ijc4ZGM1ZWZhNzFjMTM3NGFhNjc5YTFhNDk5M2Y5YjEwIiwibmJmIjoxNTc1NDExNjcyLCJleHAiOjE1NzU0MTE5NzIsImlhdCI6MTU3NTQxMTY3MiwiaXNzIjoiSHlwZXJhdGl2YSBIeXBlclBsYXRhZm9ybWEiLCJhdWQiOiJIeXBlcmF0aXZhIENsaWVudCBBcHBsaWNhdGlvbnMifQ._emJ8KeQDn5UTP2kZIXdzVXpnvF1En0UnfCxoDexwJScp2YvIoJMCw3_6iDHzXc7H4PZ7RwkD03hpXWwMM_85A';
        let body = baseController.getObjectMapper().mapObject({
  "campaignId": 1,
  "subCampaign": {
    "subCampaignId": 169,
    "properties": [
      {
        "name": "cause",
        "value": "crianca-adolescente"
      },
      {
        "name": "institution",
        "value": "projeto_guri"
      }
    ]
  },
  "client": {
    "firstName": "Dock",
    "lastName": "tech",
    "phoneNumber": "011985654123",
    "document": "36952145586",
    "documentType": "cpf",
    "email": "email.docke@dock.tech",
    "cards": [
      {
        "cardNumber": "4001364308538553",
        "nameOnCard": "CLIENT CARD NAME"
      }
    ],
    "externalClientId": "553",
    "communicationOptin": [
      "sms"
    ]
  }
}, 'MOneclickEnrollmentsrequest');

        controller.createOneclickEnrollments(contentType, authorization, accessToken, body, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        }).catch(() => undefined);
    });

    /**
     * TODO: Add Description
     */
    it("should testMOneclickCauses response", function testMOneclickCausesTest(done) {
        // parameters for the API call
        let authorization = '{{tokenOauth}}';
        let accessToken = 'dLAMUUb5PTGMl27ic8o5mQLWQ0I8UiyJ8eqq-Vgg_FYvoQ5LeKOwsNZa8e0nmbn_NfXoBydcbpLRS90zPJBzo7pnBJglxPKf_giE2IqN3vFHeoFD5nCnUMTtY_NWqbyJZcEeKB9LV06a_X_0LxH0jUlm6EW1xP8yx_zWO4lxXzhNgtgQw8VcXh7Pjygnj7rDDr7msYg_RI5xfA--qIK-fRHquUOsRkTAGuKI-z1xt9pa85KXw0_fuWcJh0MydKTyNcAE5SFiCWAKPb-qCZuIi-Swaa5VW5qDh4MUkqZ5MhHcvtOfcgiN0hvDF-3uROht';

        controller.getOneclickCauses(authorization, accessToken, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        }).catch(() => undefined);
    });

    /**
     * TODO: Add Description
     */
    it("should testMOneclickCausesMe response", function testMOneclickCausesMeTest(done) {
        // parameters for the API call
        let authorization = '{{tokenOauth}}';
        let accessToken = 'dLAMUUb5PTGMl27ic8o5mQLWQ0I8UiyJ8eqq-Vgg_FYvoQ5LeKOwsNZa8e0nmbn_NfXoBydcbpLRS90zPJBzo7pnBJglxPKf_giE2IqN3vFHeoFD5nCnUMTtY_NWqbyJZcEeKB9LV06a_X_0LxH0jUlm6EW1xP8yx_zWO4lxXzhNgtgQw8VcXh7Pjygnj7rDDr7msYg_RI5xfA--qIK-fRHquUOsRkTAGuKI-z1xt9pa85KXw0_fuWcJh0MydKTyNcAE5SFiCWAKPb-qCZuIi-Swaa5VW5qDh4MUkqZ5MhHcvtOfcgiN0hvDF-3uROht';

        controller.getOneclickCausesMe(authorization, accessToken, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        }).catch(() => undefined);
    });
});
