/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of AdditionalOutputData
 */
class AdditionalOutputData extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.idNumber = this.constructor.getValue(obj.idNumber || obj.IdNumber);
        this.status = this.constructor.getValue(obj.status || obj.Status);
        this.certificateNumber =
          this.constructor.getValue(obj.certificateNumber
     || obj.CertificateNumber);
        this.certificateText =
          this.constructor.getValue(obj.certificateText
     || obj.CertificateText);
        this.emissionDate = this.constructor.getValue(obj.emissionDate || obj.EmissionDate);
        this.validity = this.constructor.getValue(obj.validity || obj.Validity);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'idNumber', realName: 'IdNumber' },
            { name: 'status', realName: 'Status' },
            { name: 'certificateNumber', realName: 'CertificateNumber' },
            { name: 'certificateText', realName: 'CertificateText' },
            { name: 'emissionDate', realName: 'EmissionDate' },
            { name: 'validity', realName: 'Validity' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = AdditionalOutputData;
