/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Beneficiary
 */
class Beneficiary extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.type = this.constructor.getValue(obj.type);
        this.docIdCpfCnpjEinSSN = this.constructor.getValue(obj.docIdCpfCnpjEinSSN);
        this.name = this.constructor.getValue(obj.name);
        this.bankId = this.constructor.getValue(obj.bankId);
        this.agency = this.constructor.getValue(obj.agency);
        this.agencyDigit = this.constructor.getValue(obj.agencyDigit);
        this.account = this.constructor.getValue(obj.account);
        this.accountDigit = this.constructor.getValue(obj.accountDigit);
        this.accountType = this.constructor.getValue(obj.accountType);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'type', realName: 'type' },
            { name: 'docIdCpfCnpjEinSSN', realName: 'docIdCpfCnpjEinSSN' },
            { name: 'name', realName: 'name' },
            { name: 'bankId', realName: 'bankId' },
            { name: 'agency', realName: 'agency' },
            { name: 'agencyDigit', realName: 'agencyDigit' },
            { name: 'account', realName: 'account' },
            { name: 'accountDigit', realName: 'accountDigit' },
            { name: 'accountType', realName: 'accountType' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Beneficiary;
