/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Client
 */
class Client extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.firstName = this.constructor.getValue(obj.firstName);
        this.lastName = this.constructor.getValue(obj.lastName);
        this.phoneNumber = this.constructor.getValue(obj.phoneNumber);
        this.document = this.constructor.getValue(obj.document);
        this.documentType = this.constructor.getValue(obj.documentType);
        this.email = this.constructor.getValue(obj.email);
        this.cards = this.constructor.getValue(obj.cards);
        this.externalClientId = this.constructor.getValue(obj.externalClientId);
        this.communicationOptin = this.constructor.getValue(obj.communicationOptin);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'firstName', realName: 'firstName' },
            { name: 'lastName', realName: 'lastName' },
            { name: 'phoneNumber', realName: 'phoneNumber' },
            { name: 'document', realName: 'document' },
            { name: 'documentType', realName: 'documentType' },
            { name: 'email', realName: 'email' },
            { name: 'cards', realName: 'cards', array: true, type: 'Card' },
            { name: 'externalClientId', realName: 'externalClientId' },
            { name: 'communicationOptin', realName: 'communicationOptin', array: true },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Client;
