/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Company10
 */
class Company10 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.legalName = this.constructor.getValue(obj.legalName);
        this.stateRegistration = this.constructor.getValue(obj.stateRegistration);
        this.tradeName = this.constructor.getValue(obj.tradeName);
        this.revenue = this.constructor.getValue(obj.revenue);
        this.establishmentDate = this.constructor.getValue(obj.establishmentDate);
        this.legalNature = this.constructor.getValue(obj.legalNature);
        this.legalStatus = this.constructor.getValue(obj.legalStatus);
        this.nationalRegistration = this.constructor.getValue(obj.nationalRegistration);
        this.establishmentFormat = this.constructor.getValue(obj.establishmentFormat);
        this.email = this.constructor.getValue(obj.email);
        this.mainCnae = this.constructor.getValue(obj.mainCnae);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'legalName', realName: 'legalName' },
            { name: 'stateRegistration', realName: 'stateRegistration' },
            { name: 'tradeName', realName: 'tradeName' },
            { name: 'revenue', realName: 'revenue' },
            { name: 'establishmentDate', realName: 'establishmentDate' },
            { name: 'legalNature', realName: 'legalNature' },
            { name: 'legalStatus', realName: 'legalStatus' },
            { name: 'nationalRegistration', realName: 'nationalRegistration' },
            { name: 'establishmentFormat', realName: 'establishmentFormat' },
            { name: 'email', realName: 'email' },
            { name: 'mainCnae', realName: 'mainCnae' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Company10;
