/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Individual
 */
class Individual extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.isPep = this.constructor.getValue(obj.isPep);
        this.profile = this.constructor.getValue(obj.profile);
        this.type = this.constructor.getValue(obj.type);
        this.name = this.constructor.getValue(obj.name);
        this.birthDate = this.constructor.getValue(obj.birthDate);
        this.motherName = this.constructor.getValue(obj.motherName);
        this.gender = this.constructor.getValue(obj.gender);
        this.maritalStatus = this.constructor.getValue(obj.maritalStatus);
        this.email = this.constructor.getValue(obj.email);
        this.occupation = this.constructor.getValue(obj.occupation);
        this.pep = this.constructor.getValue(obj.pep);
        this.revenue = this.constructor.getValue(obj.revenue);
        this.nationalRegistration = this.constructor.getValue(obj.nationalRegistration);
        this.identityCard = this.constructor.getValue(obj.identityCard);
        this.mainPhone = this.constructor.getValue(obj.mainPhone);
        this.phones = this.constructor.getValue(obj.phones);
        this.mainAddress = this.constructor.getValue(obj.mainAddress);
        this.addresses = this.constructor.getValue(obj.addresses);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'isPep', realName: 'isPep' },
            { name: 'profile', realName: 'profile' },
            { name: 'type', realName: 'type', array: true },
            { name: 'name', realName: 'name' },
            { name: 'birthDate', realName: 'birthDate' },
            { name: 'motherName', realName: 'motherName' },
            { name: 'gender', realName: 'gender' },
            { name: 'maritalStatus', realName: 'maritalStatus' },
            { name: 'email', realName: 'email' },
            { name: 'occupation', realName: 'occupation' },
            { name: 'pep', realName: 'pep' },
            { name: 'revenue', realName: 'revenue' },
            { name: 'nationalRegistration', realName: 'nationalRegistration' },
            { name: 'identityCard', realName: 'identityCard', type: 'IdentityCard' },
            { name: 'mainPhone', realName: 'mainPhone', type: 'MainPhone' },
            { name: 'phones', realName: 'phones', array: true, type: 'Phone' },
            { name: 'mainAddress', realName: 'mainAddress', type: 'MainAddress' },
            { name: 'addresses', realName: 'addresses', array: true, type: 'Address1' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Individual;
