/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of MApiCartoesIdConsultarDadosReais
 */
class MApiCartoesIdConsultarDadosReais extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.flagVirtual = this.constructor.getValue(obj.flagVirtual);
        this.numeroCartao = this.constructor.getValue(obj.numeroCartao);
        this.dataValidade = this.constructor.getValue(obj.dataValidade);
        this.cvv2 = this.constructor.getValue(obj.cvv2);
        this.nomePlastico = this.constructor.getValue(obj.nomePlastico);
        this.idConta = this.constructor.getValue(obj.idConta);
        this.idCartao = this.constructor.getValue(obj.idCartao);
        this.numeroAgencia = this.constructor.getValue(obj.numeroAgencia);
        this.numeroContaCorente = this.constructor.getValue(obj.numeroContaCorente);
        this.idStatusConta = this.constructor.getValue(obj.idStatusConta);
        this.statusConta = this.constructor.getValue(obj.statusConta);
        this.idStatusCartao = this.constructor.getValue(obj.idStatusCartao);
        this.statusCartao = this.constructor.getValue(obj.statusCartao);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'flagVirtual', realName: 'flagVirtual' },
            { name: 'numeroCartao', realName: 'numeroCartao' },
            { name: 'dataValidade', realName: 'dataValidade' },
            { name: 'cvv2', realName: 'cvv2' },
            { name: 'nomePlastico', realName: 'nomePlastico' },
            { name: 'idConta', realName: 'idConta' },
            { name: 'idCartao', realName: 'idCartao' },
            { name: 'numeroAgencia', realName: 'numeroAgencia' },
            { name: 'numeroContaCorente', realName: 'numeroContaCorente' },
            { name: 'idStatusConta', realName: 'idStatusConta' },
            { name: 'statusConta', realName: 'statusConta' },
            { name: 'idStatusCartao', realName: 'idStatusCartao' },
            { name: 'statusCartao', realName: 'statusCartao' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = MApiCartoesIdConsultarDadosReais;
