/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of MContasIdAdicionaisIdPessoaRequest
 */
class MContasIdAdicionaisIdPessoaRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.nome = this.constructor.getValue(obj.nome);
        this.nomeImpresso = this.constructor.getValue(obj.nomeImpresso);
        this.numeroReceitaFederal = this.constructor.getValue(obj.numeroReceitaFederal);
        this.dataNascimento = this.constructor.getValue(obj.dataNascimento);
        this.sexo = this.constructor.getValue(obj.sexo);
        this.numeroIdentidade = this.constructor.getValue(obj.numeroIdentidade);
        this.orgaoExpedidorIdentidade = this.constructor.getValue(obj.orgaoExpedidorIdentidade);
        this.unidadeFederativaIdentidade =
          this.constructor.getValue(obj.unidadeFederativaIdentidade);
        this.dataEmissaoIdentidade = this.constructor.getValue(obj.dataEmissaoIdentidade);
        this.idParentesco = this.constructor.getValue(obj.idParentesco);
        this.telefones = this.constructor.getValue(obj.telefones);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'nome', realName: 'nome' },
            { name: 'nomeImpresso', realName: 'nomeImpresso' },
            { name: 'numeroReceitaFederal', realName: 'numeroReceitaFederal' },
            { name: 'dataNascimento', realName: 'dataNascimento' },
            { name: 'sexo', realName: 'sexo' },
            { name: 'numeroIdentidade', realName: 'numeroIdentidade' },
            { name: 'orgaoExpedidorIdentidade', realName: 'orgaoExpedidorIdentidade' },
            { name: 'unidadeFederativaIdentidade', realName: 'unidadeFederativaIdentidade' },
            { name: 'dataEmissaoIdentidade', realName: 'dataEmissaoIdentidade' },
            { name: 'idParentesco', realName: 'idParentesco' },
            { name: 'telefones', realName: 'telefones', array: true, type: 'Telefones3' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = MContasIdAdicionaisIdPessoaRequest;
