/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of MContasIdAccountAlterarProdutoRequest
 */
class MContasIdAccountAlterarProdutoRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.idProduto = this.constructor.getValue(obj.idProduto);
        this.idOrigemComercial = this.constructor.getValue(obj.idOrigemComercial);
        this.idEstabelecimento = this.constructor.getValue(obj.idEstabelecimento);
        this.idPromotor = this.constructor.getValue(obj.idPromotor);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'idProduto', realName: 'idProduto' },
            { name: 'idOrigemComercial', realName: 'idOrigemComercial' },
            { name: 'idEstabelecimento', realName: 'idEstabelecimento' },
            { name: 'idPromotor', realName: 'idPromotor' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = MContasIdAccountAlterarProdutoRequest;
