/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of MContasIdAdicionaisIdPessoa
 */
class MContasIdAdicionaisIdPessoa extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.idConta = this.constructor.getValue(obj.idConta);
        this.idPessoa = this.constructor.getValue(obj.idPessoa);
        this.nome = this.constructor.getValue(obj.nome);
        this.nomeImpresso = this.constructor.getValue(obj.nomeImpresso);
        this.numeroReceitaFederal = this.constructor.getValue(obj.numeroReceitaFederal);
        this.dataNascimento = this.constructor.getValue(obj.dataNascimento);
        this.sexo = this.constructor.getValue(obj.sexo);
        this.numeroIdentidade = this.constructor.getValue(obj.numeroIdentidade);
        this.orgaoExpedidorIdentidade = this.constructor.getValue(obj.orgaoExpedidorIdentidade);
        this.unidadeFederativaIdentidade =
          this.constructor.getValue(obj.unidadeFederativaIdentidade);
        this.dataEmissaoIdentidade = this.constructor.getValue(obj.dataEmissaoIdentidade);
        this.idParentesco = this.constructor.getValue(obj.idParentesco);
        this.idEstadoCivil = this.constructor.getValue(obj.idEstadoCivil);
        this.idProfissao = this.constructor.getValue(obj.idProfissao);
        this.idNacionalidade = this.constructor.getValue(obj.idNacionalidade);
        this.email = this.constructor.getValue(obj.email);
        this.flagAtivo = this.constructor.getValue(obj.flagAtivo);
        this.dataCadastroPortador = this.constructor.getValue(obj.dataCadastroPortador);
        this.dataCancelamentoPortador = this.constructor.getValue(obj.dataCancelamentoPortador);
        this.telefones = this.constructor.getValue(obj.telefones);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'idConta', realName: 'idConta' },
            { name: 'idPessoa', realName: 'idPessoa' },
            { name: 'nome', realName: 'nome' },
            { name: 'nomeImpresso', realName: 'nomeImpresso' },
            { name: 'numeroReceitaFederal', realName: 'numeroReceitaFederal' },
            { name: 'dataNascimento', realName: 'dataNascimento' },
            { name: 'sexo', realName: 'sexo' },
            { name: 'numeroIdentidade', realName: 'numeroIdentidade' },
            { name: 'orgaoExpedidorIdentidade', realName: 'orgaoExpedidorIdentidade' },
            { name: 'unidadeFederativaIdentidade', realName: 'unidadeFederativaIdentidade' },
            { name: 'dataEmissaoIdentidade', realName: 'dataEmissaoIdentidade' },
            { name: 'idParentesco', realName: 'idParentesco' },
            { name: 'idEstadoCivil', realName: 'idEstadoCivil' },
            { name: 'idProfissao', realName: 'idProfissao' },
            { name: 'idNacionalidade', realName: 'idNacionalidade' },
            { name: 'email', realName: 'email' },
            { name: 'flagAtivo', realName: 'flagAtivo' },
            { name: 'dataCadastroPortador', realName: 'dataCadastroPortador' },
            { name: 'dataCancelamentoPortador', realName: 'dataCancelamentoPortador' },
            { name: 'telefones', realName: 'telefones', array: true, type: 'Telefones3' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = MContasIdAdicionaisIdPessoa;
