/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of MOauth2Token
 */
class MOauth2Token extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.accessToken = this.constructor.getValue(obj.accessToken || obj.access_token);
        this.expiresIn = this.constructor.getValue(obj.expiresIn || obj.expires_in);
        this.tokenType = this.constructor.getValue(obj.tokenType || obj.token_type);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'accessToken', realName: 'access_token' },
            { name: 'expiresIn', realName: 'expires_in' },
            { name: 'tokenType', realName: 'token_type' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = MOauth2Token;
