/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of MP2ptransferDetailsIdAccount
 */
class MP2ptransferDetailsIdAccount extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.transactionCode = this.constructor.getValue(obj.transactionCode);
        this.originalAccount = this.constructor.getValue(obj.originalAccount);
        this.destinationAccount = this.constructor.getValue(obj.destinationAccount);
        this.amount = this.constructor.getValue(obj.amount);
        this.date = this.constructor.getValue(obj.date);
        this.description = this.constructor.getValue(obj.description);
        this.idAdjustment = this.constructor.getValue(obj.idAdjustment);
        this.idIssuer = this.constructor.getValue(obj.idIssuer);
        this.transactionTariffCode = this.constructor.getValue(obj.transactionTariffCode);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'transactionCode', realName: 'transactionCode' },
            { name: 'originalAccount', realName: 'originalAccount' },
            { name: 'destinationAccount', realName: 'destinationAccount' },
            { name: 'amount', realName: 'amount' },
            { name: 'date', realName: 'date' },
            { name: 'description', realName: 'description' },
            { name: 'idAdjustment', realName: 'idAdjustment' },
            { name: 'idIssuer', realName: 'idIssuer' },
            { name: 'transactionTariffCode', realName: 'transactionTariffCode' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = MP2ptransferDetailsIdAccount;
