/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of MPaymentsAccountIdAccount
 */
class MPaymentsAccountIdAccount extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.idAdjustment = this.constructor.getValue(obj.idAdjustment);
        this.idIssuer = this.constructor.getValue(obj.idIssuer);
        this.uniqueIdDablan = this.constructor.getValue(obj.uniqueIdDablan);
        this.account = this.constructor.getValue(obj.account);
        this.amount = this.constructor.getValue(obj.amount);
        this.barCode = this.constructor.getValue(obj.barCode);
        this.dueDate = this.constructor.getValue(obj.dueDate);
        this.description = this.constructor.getValue(obj.description);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'idAdjustment', realName: 'idAdjustment' },
            { name: 'idIssuer', realName: 'idIssuer' },
            { name: 'uniqueIdDablan', realName: 'uniqueIdDablan' },
            { name: 'account', realName: 'account' },
            { name: 'amount', realName: 'amount' },
            { name: 'barCode', realName: 'barCode' },
            { name: 'dueDate', realName: 'dueDate' },
            { name: 'description', realName: 'description' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = MPaymentsAccountIdAccount;
