/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of OnlineCertificate
 */
class OnlineCertificate extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.origin = this.constructor.getValue(obj.origin || obj.Origin);
        this.inputParameters =
          this.constructor.getValue(obj.inputParameters
     || obj.InputParameters);
        this.additionalOutputData =
          this.constructor.getValue(obj.additionalOutputData
     || obj.AdditionalOutputData);
        this.queryDate = this.constructor.getValue(obj.queryDate || obj.QueryDate);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'origin', realName: 'Origin' },
            { name: 'inputParameters', realName: 'InputParameters' },
            {
                name: 'additionalOutputData',
                realName: 'AdditionalOutputData',
                type: 'AdditionalOutputData',
            },
            { name: 'queryDate', realName: 'QueryDate' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = OnlineCertificate;
