/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Phone12
 */
class Phone12 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.area = this.constructor.getValue(obj.area);
        this.number = this.constructor.getValue(obj.number);
        this.type = this.constructor.getValue(obj.type);
        this.countryCode = this.constructor.getValue(obj.countryCode);
        this.idPhoneType = this.constructor.getValue(obj.idPhoneType);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'area', realName: 'area' },
            { name: 'number', realName: 'number' },
            { name: 'type', realName: 'type' },
            { name: 'countryCode', realName: 'countryCode' },
            { name: 'idPhoneType', realName: 'idPhoneType' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Phone12;
