/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ProductSettings
 */
class ProductSettings extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.printedCardName = this.constructor.getValue(obj.printedCardName);
        this.externalAccountNumber = this.constructor.getValue(obj.externalAccountNumber);
        this.termsAndConditionsTokens = this.constructor.getValue(obj.termsAndConditionsTokens);
        this.deviceIdentification = this.constructor.getValue(obj.deviceIdentification);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'printedCardName', realName: 'printedCardName' },
            { name: 'externalAccountNumber', realName: 'externalAccountNumber' },
            { name: 'termsAndConditionsTokens', realName: 'termsAndConditionsTokens', array: true },
            {
                name: 'deviceIdentification',
                realName: 'deviceIdentification',
                type: 'DeviceIdentification',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ProductSettings;
