/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Result5
 */
class Result5 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.nationalRegistration = this.constructor.getValue(obj.nationalRegistration);
        this.company = this.constructor.getValue(obj.company);
        this.productSettings = this.constructor.getValue(obj.productSettings);
        this.status = this.constructor.getValue(obj.status);
        this.created = this.constructor.getValue(obj.created);
        this.registrationId = this.constructor.getValue(obj.registrationId);
        this.issuerId = this.constructor.getValue(obj.issuerId);
        this.notes = this.constructor.getValue(obj.notes);
        this.statusHistory = this.constructor.getValue(obj.statusHistory);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'nationalRegistration', realName: 'nationalRegistration' },
            { name: 'company', realName: 'company', type: 'Company8' },
            { name: 'productSettings', realName: 'productSettings', type: 'ProductSettings4' },
            { name: 'status', realName: 'status' },
            { name: 'created', realName: 'created' },
            { name: 'registrationId', realName: 'registrationId' },
            { name: 'issuerId', realName: 'issuerId' },
            { name: 'notes', realName: 'notes', array: true },
            {
                name: 'statusHistory',
                realName: 'statusHistory',
                array: true,
                type: 'StatusHistory',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Result5;
