/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Sanctions
 */
class Sanctions extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.pEPHistory = this.constructor.getValue(obj.pEPHistory || obj.PEPHistory);
        this.isCurrentlyPEP = this.constructor.getValue(obj.isCurrentlyPEP || obj.IsCurrentlyPEP);
        this.sanctionsHistory =
          this.constructor.getValue(obj.sanctionsHistory
     || obj.SanctionsHistory);
        this.isCurrentlySanctioned =
          this.constructor.getValue(obj.isCurrentlySanctioned
     || obj.IsCurrentlySanctioned);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'pEPHistory', realName: 'PEPHistory', array: true },
            { name: 'isCurrentlyPEP', realName: 'IsCurrentlyPEP' },
            {
                name: 'sanctionsHistory',
                realName: 'SanctionsHistory',
                array: true,
                type: 'SanctionsHistory',
            },
            { name: 'isCurrentlySanctioned', realName: 'IsCurrentlySanctioned' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Sanctions;
