/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Telefones3
 */
class Telefones3 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.idTipoTelefone = this.constructor.getValue(obj.idTipoTelefone);
        this.ddd = this.constructor.getValue(obj.ddd);
        this.telefone = this.constructor.getValue(obj.telefone);
        this.ramal = this.constructor.getValue(obj.ramal);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'idTipoTelefone', realName: 'idTipoTelefone' },
            { name: 'ddd', realName: 'ddd' },
            { name: 'telefone', realName: 'telefone' },
            { name: 'ramal', realName: 'ramal' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Telefones3;
