/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const MOauth2Token = require('../lib/Models/MOauth2Token');
const MRegistrationsrequest = require('../lib/Models/MRegistrationsrequest');
const Company = require('../lib/Models/Company');
const MainPhone = require('../lib/Models/MainPhone');
const Phone = require('../lib/Models/Phone');
const MainAddress = require('../lib/Models/MainAddress');
const Address = require('../lib/Models/Address');
const Partners = require('../lib/Models/Partners');
const Individual = require('../lib/Models/Individual');
const IdentityCard = require('../lib/Models/IdentityCard');
const Address1 = require('../lib/Models/Address1');
const Company1 = require('../lib/Models/Company1');
const ProductSettings = require('../lib/Models/ProductSettings');
const DeviceIdentification = require('../lib/Models/DeviceIdentification');
const MRegistrations = require('../lib/Models/MRegistrations');
const Result = require('../lib/Models/Result');
const HttpsCompaniesHmlCaradhrasIoV1Registrations791d1dbeF6cd48cdA21bDce0dbd83201DocumentsDocumentTypePASSPORT =
  require('../lib/Models/HttpsCompaniesHmlCaradhrasIoV1Registrations791d1dbeF6cd48cdA21bDce0dbd83201DocumentsDocumentTypePASSPORT');
const Result1 = require('../lib/Models/Result1');
const MRegistrationsRegistrationIdRequest =
  require('../lib/Models/MRegistrationsRegistrationIdRequest');
const MRegistrationsRegistrationId = require('../lib/Models/MRegistrationsRegistrationId');
const MRegisteredCompaniesCompanyIdRequest =
  require('../lib/Models/MRegisteredCompaniesCompanyIdRequest');
const MRegisteredCompanies9914293 = require('../lib/Models/MRegisteredCompanies9914293');
const MRegistrations791d1dbeF6cd48cdA21bDce0dbd83201 =
  require('../lib/Models/MRegistrations791d1dbeF6cd48cdA21bDce0dbd83201');
const Result3 = require('../lib/Models/Result3');
const Company6 = require('../lib/Models/Company6');
const Partners3 = require('../lib/Models/Partners3');
const Individual3 = require('../lib/Models/Individual3');
const MRegistrationsRegistrationIdC6f09995Af8c4e0f89f41beca1da7b5fDocuments =
  require('../lib/Models/MRegistrationsRegistrationIdC6f09995Af8c4e0f89f41beca1da7b5fDocuments');
const Result4 = require('../lib/Models/Result4');
const MRegistrationsStatusesStatus = require('../lib/Models/MRegistrationsStatusesStatus');
const Result5 = require('../lib/Models/Result5');
const Company8 = require('../lib/Models/Company8');
const Address12 = require('../lib/Models/Address12');
const MainPhone12 = require('../lib/Models/MainPhone12');
const Phone12 = require('../lib/Models/Phone12');
const MainAddress12 = require('../lib/Models/MainAddress12');
const Partners4 = require('../lib/Models/Partners4');
const Individual4 = require('../lib/Models/Individual4');
const MainPhone13 = require('../lib/Models/MainPhone13');
const Company9 = require('../lib/Models/Company9');
const Company10 = require('../lib/Models/Company10');
const ProductSettings4 = require('../lib/Models/ProductSettings4');
const TermsAndConditionsTokens = require('../lib/Models/TermsAndConditionsTokens');
const StatusHistory = require('../lib/Models/StatusHistory');
const MRegistrationsCompaniesCNPJPartnersCPF =
  require('../lib/Models/MRegistrationsCompaniesCNPJPartnersCPF');
const Result6 = require('../lib/Models/Result6');
const Partner = require('../lib/Models/Partner');
const MRegisteredCompanies99142931 = require('../lib/Models/MRegisteredCompanies99142931');
const Result7 = require('../lib/Models/Result7');
const MIndividualsAccounts = require('../lib/Models/MIndividualsAccounts');
const Address19 = require('../lib/Models/Address19');
const Phone19 = require('../lib/Models/Phone19');
const MIndividualsrequest = require('../lib/Models/MIndividualsrequest');
const Address20 = require('../lib/Models/Address20');
const Phone20 = require('../lib/Models/Phone20');
const MIndividualsRegisteredUnderContingency =
  require('../lib/Models/MIndividualsRegisteredUnderContingency');
const MIndividuals = require('../lib/Models/MIndividuals');
const Item = require('../lib/Models/Item');
const MIndividualsId = require('../lib/Models/MIndividualsId');
const MIndividualsId1 = require('../lib/Models/MIndividualsId1');
const MIndividualsAccountsAccountIdAdditionalsRequest =
  require('../lib/Models/MIndividualsAccountsAccountIdAdditionalsRequest');
const MEnderecos = require('../lib/Models/MEnderecos');
const MEnderecosId = require('../lib/Models/MEnderecosId');
const MEnderecosId2 = require('../lib/Models/MEnderecosId2');
const MTelefones = require('../lib/Models/MTelefones');
const MTelefonesId = require('../lib/Models/MTelefonesId');
const MTelefones1 = require('../lib/Models/MTelefones1');
const Content = require('../lib/Models/Content');
const MEnderecosCorrespondenciaId = require('../lib/Models/MEnderecosCorrespondenciaId');
const MContasIdVinculosrequest = require('../lib/Models/MContasIdVinculosrequest');
const MContasIdVinculos = require('../lib/Models/MContasIdVinculos');
const MContasVinculosTiposrequest = require('../lib/Models/MContasVinculosTiposrequest');
const MContasIdVinculosTipos = require('../lib/Models/MContasIdVinculosTipos');
const MContasIdAtribuirCartaoPrepagoRequest =
  require('../lib/Models/MContasIdAtribuirCartaoPrepagoRequest');
const MContasIdVinculos1 = require('../lib/Models/MContasIdVinculos1');
const Content1 = require('../lib/Models/Content1');
const MContasIdVinculosTipos1 = require('../lib/Models/MContasIdVinculosTipos1');
const Content2 = require('../lib/Models/Content2');
const MContasId = require('../lib/Models/MContasId');
const MContas = require('../lib/Models/MContas');
const Content3 = require('../lib/Models/Content3');
const MContasId1 = require('../lib/Models/MContasId1');
const MContasIdAccountsAdicionais = require('../lib/Models/MContasIdAccountsAdicionais');
const MContasIdAccountAdicionais = require('../lib/Models/MContasIdAccountAdicionais');
const MContasIdAdicionaisIdPessoaRequest =
  require('../lib/Models/MContasIdAdicionaisIdPessoaRequest');
const Telefones3 = require('../lib/Models/Telefones3');
const MContasIdAdicionaisIdPessoa = require('../lib/Models/MContasIdAdicionaisIdPessoa');
const MContasIdPessoasIdPessoaPortadoresRequest =
  require('../lib/Models/MContasIdPessoasIdPessoaPortadoresRequest');
const MContasIdBloquear = require('../lib/Models/MContasIdBloquear');
const MContasIdAccountAlterarProdutoRequest =
  require('../lib/Models/MContasIdAccountAlterarProdutoRequest');
const MContasIdTimeline = require('../lib/Models/MContasIdTimeline');
const Content4 = require('../lib/Models/Content4');
const MContasIdTransacoes = require('../lib/Models/MContasIdTransacoes');
const Content5 = require('../lib/Models/Content5');
const MBanktransfers = require('../lib/Models/MBanktransfers');
const Beneficiary = require('../lib/Models/Beneficiary');
const MBanktransfersAccountIdAccount = require('../lib/Models/MBanktransfersAccountIdAccount');
const MBanktransfersAdjustmentIdAdjustment =
  require('../lib/Models/MBanktransfersAdjustmentIdAdjustment');
const MBillet = require('../lib/Models/MBillet');
const MPaymentsliprequest = require('../lib/Models/MPaymentsliprequest');
const PayingSource = require('../lib/Models/PayingSource');
const BankSlip = require('../lib/Models/BankSlip');
const MBoletos = require('../lib/Models/MBoletos');
const Content6 = require('../lib/Models/Content6');
const MContasIdAccountGerarCartaoProvisorio =
  require('../lib/Models/MContasIdAccountGerarCartaoProvisorio');
const MCartoes = require('../lib/Models/MCartoes');
const Content7 = require('../lib/Models/Content7');
const MCartoesIdCard = require('../lib/Models/MCartoesIdCard');
const MCartoesIdCardGerarNovaVia = require('../lib/Models/MCartoesIdCardGerarNovaVia');
const MCartoesIdCardDesbloquearSenhaIncorreta =
  require('../lib/Models/MCartoesIdCardDesbloquearSenhaIncorreta');
const MCartoesIdCardValidarSenha = require('../lib/Models/MCartoesIdCardValidarSenha');
const MCartoesIdCardBloquear = require('../lib/Models/MCartoesIdCardBloquear');
const MCartoesIdCardDesbloquear = require('../lib/Models/MCartoesIdCardDesbloquear');
const MCartoesIdCardCancelar = require('../lib/Models/MCartoesIdCardCancelar');
const MStatusCartoes = require('../lib/Models/MStatusCartoes');
const Content8 = require('../lib/Models/Content8');
const MStatusCatoesIdCard = require('../lib/Models/MStatusCatoesIdCard');
const MCartoesIdAlterarEstagio = require('../lib/Models/MCartoesIdAlterarEstagio');
const MCartoesIdCardValidarCvvRequest = require('../lib/Models/MCartoesIdCardValidarCvvRequest');
const MCartoesLotesCartoesPrePagos = require('../lib/Models/MCartoesLotesCartoesPrePagos');
const MCartoesLotesCartoesPrePagosId = require('../lib/Models/MCartoesLotesCartoesPrePagosId');
const MCartoesIdCardLimitesDisponibilidades =
  require('../lib/Models/MCartoesIdCardLimitesDisponibilidades');
const MCartoesIdCardAtribuirTitular = require('../lib/Models/MCartoesIdCardAtribuirTitular');
const MApiCartoesIdConsultarDadosReais = require('../lib/Models/MApiCartoesIdConsultarDadosReais');
const MCartoesIdConsultarDadosImpressao =
  require('../lib/Models/MCartoesIdConsultarDadosImpressao');
const DocumentsValidation = require('../lib/Models/DocumentsValidation');
const Result8 = require('../lib/Models/Result8');
const DocumentsValidationRules = require('../lib/Models/DocumentsValidationRules');
const Instructions = require('../lib/Models/Instructions');
const Header = require('../lib/Models/Header');
const ContentType = require('../lib/Models/ContentType');
const Params = require('../lib/Models/Params');
const Person = require('../lib/Models/Person');
const Category = require('../lib/Models/Category');
const Side = require('../lib/Models/Side');
const Body = require('../lib/Models/Body');
const SelfiesValidation = require('../lib/Models/SelfiesValidation');
const SelfiesValidationRules = require('../lib/Models/SelfiesValidationRules');
const Instructions1 = require('../lib/Models/Instructions1');
const Header1 = require('../lib/Models/Header1');
const ContentType1 = require('../lib/Models/ContentType1');
const Params1 = require('../lib/Models/Params1');
const MKnowyourclientPeople = require('../lib/Models/MKnowyourclientPeople');
const BasicData = require('../lib/Models/BasicData');
const Address23 = require('../lib/Models/Address23');
const Phone23 = require('../lib/Models/Phone23');
const Sanctions = require('../lib/Models/Sanctions');
const SanctionsHistory = require('../lib/Models/SanctionsHistory');
const Details = require('../lib/Models/Details');
const Collections = require('../lib/Models/Collections');
const Score = require('../lib/Models/Score');
const OnlineCertificate = require('../lib/Models/OnlineCertificate');
const AdditionalOutputData = require('../lib/Models/AdditionalOutputData');
const MCeps = require('../lib/Models/MCeps');
const MBancos = require('../lib/Models/MBancos');
const Content9 = require('../lib/Models/Content9');
const MBancosrequest = require('../lib/Models/MBancosrequest');
const MBancos1 = require('../lib/Models/MBancos1');
const MBancosIdBank = require('../lib/Models/MBancosIdBank');
const MP2ptransferrequest = require('../lib/Models/MP2ptransferrequest');
const MP2ptransfer = require('../lib/Models/MP2ptransfer');
const MP2ptransferDetailsIdAccount = require('../lib/Models/MP2ptransferDetailsIdAccount');
const MP2ptransferDetailsIdAccount1 = require('../lib/Models/MP2ptransferDetailsIdAccount1');
const MP2ptransferAdjustmentIdAdjustment =
  require('../lib/Models/MP2ptransferAdjustmentIdAdjustment');
const MTollsRechargesrequest = require('../lib/Models/MTollsRechargesrequest');
const MTollsRecharges = require('../lib/Models/MTollsRecharges');
const MTollsRechargesrequest1 = require('../lib/Models/MTollsRechargesrequest1');
const MTollsRechargesrequest2 = require('../lib/Models/MTollsRechargesrequest2');
const MTollsRecharges34943232 = require('../lib/Models/MTollsRecharges34943232');
const MTollsDownloads34943232 = require('../lib/Models/MTollsDownloads34943232');
const MPaymentsrequest = require('../lib/Models/MPaymentsrequest');
const MPaymentsAccountIdAccount = require('../lib/Models/MPaymentsAccountIdAccount');
const MPaymentsAdjustmentIdAdjustment = require('../lib/Models/MPaymentsAdjustmentIdAdjustment');
const MPaymentsV1 = require('../lib/Models/MPaymentsV1');
const MPaymentV1Schedulerrequest = require('../lib/Models/MPaymentV1Schedulerrequest');
const Payload = require('../lib/Models/Payload');
const MPaymentV1Scheduler = require('../lib/Models/MPaymentV1Scheduler');
const Result10 = require('../lib/Models/Result10');
const Payload1 = require('../lib/Models/Payload1');
const MPaymentsV1Receipts = require('../lib/Models/MPaymentsV1Receipts');
const Item1 = require('../lib/Models/Item1');
const MPaymentsV1Scheduler = require('../lib/Models/MPaymentsV1Scheduler');
const Item2 = require('../lib/Models/Item2');
const MPaymentsV1SchedulerIdSchedule = require('../lib/Models/MPaymentsV1SchedulerIdSchedule');
const MRechargesDealers1 = require('../lib/Models/MRechargesDealers1');
const Dealer = require('../lib/Models/Dealer');
const MRechargesrequest = require('../lib/Models/MRechargesrequest');
const MRecharges2 = require('../lib/Models/MRecharges2');
const Option = require('../lib/Models/Option');
const FixedAmount = require('../lib/Models/FixedAmount');
const MRechargesOrderIdRequest = require('../lib/Models/MRechargesOrderIdRequest');
const MRechargesPedido3 = require('../lib/Models/MRechargesPedido3');
const MRechargesOrderIdConfirmRequest = require('../lib/Models/MRechargesOrderIdConfirmRequest');
const MRechargesOrderIdConfirm = require('../lib/Models/MRechargesOrderIdConfirm');
const MRechargesAccountIdAccount = require('../lib/Models/MRechargesAccountIdAccount');
const MRechargesAdjustmentIdAdjustment = require('../lib/Models/MRechargesAdjustmentIdAdjustment');
const MSingleIssuerPaymentRequest = require('../lib/Models/MSingleIssuerPaymentRequest');
const MRechargesOrderIdConfirmRequest1 = require('../lib/Models/MRechargesOrderIdConfirmRequest1');
const MTransportcardsCardIdSptrans1 = require('../lib/Models/MTransportcardsCardIdSptrans1');
const Product = require('../lib/Models/Product');
const MTransportcardsRecharge2Request = require('../lib/Models/MTransportcardsRecharge2Request');
const MTransportcardsRecharge2 = require('../lib/Models/MTransportcardsRecharge2');
const MTransportcardsRechargeIdRecharge3 =
  require('../lib/Models/MTransportcardsRechargeIdRecharge3');
const MRateWaivedrequest = require('../lib/Models/MRateWaivedrequest');
const MTransportcardsCardIdSptrans11 = require('../lib/Models/MTransportcardsCardIdSptrans11');
const Product1 = require('../lib/Models/Product1');
const MTransportcardsAccountIdAccount = require('../lib/Models/MTransportcardsAccountIdAccount');
const MRegistration = require('../lib/Models/MRegistration');
const Result11 = require('../lib/Models/Result11');
const RegulatoryDocument = require('../lib/Models/RegulatoryDocument');
const RegistrationTypesType1TypesType2 = require('../lib/Models/RegistrationTypesType1TypesType2');
const Result12 = require('../lib/Models/Result12');
const RegulatoryDocument1 = require('../lib/Models/RegulatoryDocument1');
const MAgreementrequest = require('../lib/Models/MAgreementrequest');
const MOneclickEnrollmentsrequest = require('../lib/Models/MOneclickEnrollmentsrequest');
const SubCampaign = require('../lib/Models/SubCampaign');
const Property = require('../lib/Models/Property');
const Client = require('../lib/Models/Client');
const Card = require('../lib/Models/Card');
const MP2ptransferCustomizedUUIDException =
  require('../lib/Exceptions/MP2ptransferCustomizedUUIDException');
const MP2ptransferBackTransactionUUIDException =
  require('../lib/Exceptions/MP2ptransferBackTransactionUUIDException');

const classMap = {
    MOauth2Token,
    MRegistrationsrequest,
    Company,
    MainPhone,
    Phone,
    MainAddress,
    Address,
    Partners,
    Individual,
    IdentityCard,
    Address1,
    Company1,
    ProductSettings,
    DeviceIdentification,
    MRegistrations,
    Result,
    HttpsCompaniesHmlCaradhrasIoV1Registrations791d1dbeF6cd48cdA21bDce0dbd83201DocumentsDocumentTypePASSPORT,
    Result1,
    MRegistrationsRegistrationIdRequest,
    MRegistrationsRegistrationId,
    MRegisteredCompaniesCompanyIdRequest,
    MRegisteredCompanies9914293,
    MRegistrations791d1dbeF6cd48cdA21bDce0dbd83201,
    Result3,
    Company6,
    Partners3,
    Individual3,
    MRegistrationsRegistrationIdC6f09995Af8c4e0f89f41beca1da7b5fDocuments,
    Result4,
    MRegistrationsStatusesStatus,
    Result5,
    Company8,
    Address12,
    MainPhone12,
    Phone12,
    MainAddress12,
    Partners4,
    Individual4,
    MainPhone13,
    Company9,
    Company10,
    ProductSettings4,
    TermsAndConditionsTokens,
    StatusHistory,
    MRegistrationsCompaniesCNPJPartnersCPF,
    Result6,
    Partner,
    MRegisteredCompanies99142931,
    Result7,
    MIndividualsAccounts,
    Address19,
    Phone19,
    MIndividualsrequest,
    Address20,
    Phone20,
    MIndividualsRegisteredUnderContingency,
    MIndividuals,
    Item,
    MIndividualsId,
    MIndividualsId1,
    MIndividualsAccountsAccountIdAdditionalsRequest,
    MEnderecos,
    MEnderecosId,
    MEnderecosId2,
    MTelefones,
    MTelefonesId,
    MTelefones1,
    Content,
    MEnderecosCorrespondenciaId,
    MContasIdVinculosrequest,
    MContasIdVinculos,
    MContasVinculosTiposrequest,
    MContasIdVinculosTipos,
    MContasIdAtribuirCartaoPrepagoRequest,
    MContasIdVinculos1,
    Content1,
    MContasIdVinculosTipos1,
    Content2,
    MContasId,
    MContas,
    Content3,
    MContasId1,
    MContasIdAccountsAdicionais,
    MContasIdAccountAdicionais,
    MContasIdAdicionaisIdPessoaRequest,
    Telefones3,
    MContasIdAdicionaisIdPessoa,
    MContasIdPessoasIdPessoaPortadoresRequest,
    MContasIdBloquear,
    MContasIdAccountAlterarProdutoRequest,
    MContasIdTimeline,
    Content4,
    MContasIdTransacoes,
    Content5,
    MBanktransfers,
    Beneficiary,
    MBanktransfersAccountIdAccount,
    MBanktransfersAdjustmentIdAdjustment,
    MBillet,
    MPaymentsliprequest,
    PayingSource,
    BankSlip,
    MBoletos,
    Content6,
    MContasIdAccountGerarCartaoProvisorio,
    MCartoes,
    Content7,
    MCartoesIdCard,
    MCartoesIdCardGerarNovaVia,
    MCartoesIdCardDesbloquearSenhaIncorreta,
    MCartoesIdCardValidarSenha,
    MCartoesIdCardBloquear,
    MCartoesIdCardDesbloquear,
    MCartoesIdCardCancelar,
    MStatusCartoes,
    Content8,
    MStatusCatoesIdCard,
    MCartoesIdAlterarEstagio,
    MCartoesIdCardValidarCvvRequest,
    MCartoesLotesCartoesPrePagos,
    MCartoesLotesCartoesPrePagosId,
    MCartoesIdCardLimitesDisponibilidades,
    MCartoesIdCardAtribuirTitular,
    MApiCartoesIdConsultarDadosReais,
    MCartoesIdConsultarDadosImpressao,
    DocumentsValidation,
    Result8,
    DocumentsValidationRules,
    Instructions,
    Header,
    ContentType,
    Params,
    Person,
    Category,
    Side,
    Body,
    SelfiesValidation,
    SelfiesValidationRules,
    Instructions1,
    Header1,
    ContentType1,
    Params1,
    MKnowyourclientPeople,
    BasicData,
    Address23,
    Phone23,
    Sanctions,
    SanctionsHistory,
    Details,
    Collections,
    Score,
    OnlineCertificate,
    AdditionalOutputData,
    MCeps,
    MBancos,
    Content9,
    MBancosrequest,
    MBancos1,
    MBancosIdBank,
    MP2ptransferrequest,
    MP2ptransfer,
    MP2ptransferDetailsIdAccount,
    MP2ptransferDetailsIdAccount1,
    MP2ptransferAdjustmentIdAdjustment,
    MTollsRechargesrequest,
    MTollsRecharges,
    MTollsRechargesrequest1,
    MTollsRechargesrequest2,
    MTollsRecharges34943232,
    MTollsDownloads34943232,
    MPaymentsrequest,
    MPaymentsAccountIdAccount,
    MPaymentsAdjustmentIdAdjustment,
    MPaymentsV1,
    MPaymentV1Schedulerrequest,
    Payload,
    MPaymentV1Scheduler,
    Result10,
    Payload1,
    MPaymentsV1Receipts,
    Item1,
    MPaymentsV1Scheduler,
    Item2,
    MPaymentsV1SchedulerIdSchedule,
    MRechargesDealers1,
    Dealer,
    MRechargesrequest,
    MRecharges2,
    Option,
    FixedAmount,
    MRechargesOrderIdRequest,
    MRechargesPedido3,
    MRechargesOrderIdConfirmRequest,
    MRechargesOrderIdConfirm,
    MRechargesAccountIdAccount,
    MRechargesAdjustmentIdAdjustment,
    MSingleIssuerPaymentRequest,
    MRechargesOrderIdConfirmRequest1,
    MTransportcardsCardIdSptrans1,
    Product,
    MTransportcardsRecharge2Request,
    MTransportcardsRecharge2,
    MTransportcardsRechargeIdRecharge3,
    MRateWaivedrequest,
    MTransportcardsCardIdSptrans11,
    Product1,
    MTransportcardsAccountIdAccount,
    MRegistration,
    Result11,
    RegulatoryDocument,
    RegistrationTypesType1TypesType2,
    Result12,
    RegulatoryDocument1,
    MAgreementrequest,
    MOneclickEnrollmentsrequest,
    SubCampaign,
    Property,
    Client,
    Card,
    MP2ptransferCustomizedUUIDException,
    MP2ptransferBackTransactionUUIDException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
