/**
 * BaaSCaradhrasAPIDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Servers = {

    /**
     * TODO: Write general description for this element
     */
    SERVER_1: 'Server 1',

    /**
     * TODO: Write general description for this element
     */
    SERVER_2: 'Server 2',

    /**
     * TODO: Write general description for this element
     */
    SERVER_3: 'Server 3',

    /**
     * TODO: Write general description for this element
     */
    SERVER_4: 'Server 4',

    /**
     * TODO: Write general description for this element
     */
    SERVER_5: 'Server 5',

    /**
     * TODO: Write general description for this element
     */
    SERVER_6: 'Server 6',

    /**
     * TODO: Write general description for this element
     */
    SERVER_7: 'Server 7',

    /**
     * TODO: Write general description for this element
     */
    SERVER_8: 'Server 8',

};

module.exports = Servers;
